### ISSUE TITLE
Not detecting API Key

### ISSUE THREAD

**Issue by browneye1826** [arunk140/vs-code-autocomment#1]
API key added in settings but it's not seeing it for some reason:
![Image 2022-02-17 at 21 28 16](https://user-images.githubusercontent.com/59311049/154606373-082ca140-edc8-4a77-83b7-2e4285ca0aef.jpg)

**Comment by arunk140** [comment]
I was able to replicate it on one machine with a fresh install of VS Code.

Testing a few Fixes.
Will update this Issue ASAP.

**Comment by arunk140** [comment]
Pushed the 1.0.3 update with better error logging.

Please try again with the new update links below -
- [Releases](https://github.com/arunk140/vs-code-autocomment/releases/tag/stable)
- [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=arunk140.vs-code-autocomment)
- Or update it directly from the Extensions Panel in the editor
